php:
    build: .
    volumes:
        - ./wwwroot:/var/www/html
    ports:
        - 80:80
    links:
        - mysql
mysql:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=azerty
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    links:
        - mysql
